namespace MatrixOfFate.Models
{
    public class Matrix
    {
        #region Big Matrix
        public int A1 { get; set; }
        public int A2 { get; set; }
        public int A3 { get; set; }
        public int A4 { get; set; }
        public int A5 { get; set; }
        public int A6 { get; set; }
        public int A7 { get; set; }
        public int A8 { get; set; }
        public int A9 { get; set; }
        public int B1 { get; set; }
        public int B2 { get; set; }
        public int B3 { get; set; }
        public int B4 { get; set; }
        public int B5 { get; set; }
        public int B6 { get; set; }
        public int B7 { get; set; }
        public int B8 { get; set; }
        public int B9 { get; set; }
        public int C1 { get; set; }
        public int C2 { get; set; }
        public int C3 { get; set; }
        public int C4 { get; set; }
        public int C5 { get; set; }
        public int C6 { get; set; }
        public int C7 { get; set; }
        public int C8 { get; set; }
        public int C9 { get; set; }
        public int D1 { get; set; }
        public int D2 { get; set; }
        public int D3 { get; set; }
        public int D4 { get; set; }
        public int D5 { get; set; }
        public int D6 { get; set; }
        public int D7 { get; set; }
        public int D8 { get; set; }
        public int D9 { get; set; }
        public int E1 { get; set; }
        public int E2 { get; set; }
        public int E3 { get; set; }
        public int F1 { get; set; }
        public int F2 { get; set; }
        public int F3 { get; set; }
        public int F4 { get; set; }
        public int F5 { get; set; }
        public int F6 { get; set; }
        public int F7 { get; set; }
        public int G1 { get; set; }
        public int G2 { get; set; }
        public int G3 { get; set; }
        public int G4 { get; set; }
        public int G5 { get; set; }
        public int G6 { get; set; }
        public int G7 { get; set; }
        #endregion

        #region Big Matrix Table
        public string R1C1 { get; set; }
        public string R1C2 { get; set; }
        public string R1C3 { get; set; }
        public string R1C4 { get; set; }
        public string R1C5 { get; set; }
        public string R1C6 { get; set; }
        public string R1C7 { get; set; }
        public string R2C1 { get; set; }
        public string R2C2 { get; set; }
        public string R2C3 { get; set; }
        public string R2C4 { get; set; }
        public string R2C5 { get; set; }
        public string R2C6 { get; set; }
        public string R2C7 { get; set; }
        public string R3C1 { get; set; }
        public string R3C2 { get; set; }
        public string R3C3 { get; set; }
        public string R3C4 { get; set; }
        public string R3C5 { get; set; }
        public string R3C6 { get; set; }
        public string R3C7 { get; set; }
        public string R4C1 { get; set; }
        public string R4C2 { get; set; }
        public string R4C3 { get; set; }
        public string R4C4 { get; set; }
        public string R4C5 { get; set; }
        public string R4C6 { get; set; }
        public string R4C7 { get; set; }
        public string R5C1 { get; set; }
        public string R5C2 { get; set; }
        public string R5C3 { get; set; }
        public string R5C4 { get; set; }
        public string R5C5 { get; set; }
        public string R5C6 { get; set; }
        public string R5C7 { get; set; }
        public string R6C1 { get; set; }
        public string R6C2 { get; set; }
        public string R6C3 { get; set; }
        public string R6C4 { get; set; }
        public string R6C5 { get; set; }
        public string R6C6 { get; set; }
        public string R6C7 { get; set; }
        public string R7C1 { get; set; }
        public string R7C2 { get; set; }
        public string R7C3 { get; set; }
        public string R7C4 { get; set; }
        public string R7C5 { get; set; }
        public string R7C6 { get; set; }
        public string R7C7 { get; set; }
        #endregion

        #region Small Martix
        public int SA1 { get; set; }
        public int SA2 { get; set; }
        public int SA3 { get; set; }
        public int SA4 { get; set; }
        public int SA5 { get; set; }
        public int SA6 { get; set; }
        public int SA7 { get; set; }
        public int SA8 { get; set; }
        public int SA9 { get; set; }
        public int SB1 { get; set; }
        public int SB2 { get; set; }
        public int SB3 { get; set; }
        public int SB4 { get; set; }
        public int SB5 { get; set; }
        public int SB6 { get; set; }
        public int SB7 { get; set; }
        public int SB8 { get; set; }
        public int SB9 { get; set; }
        public int SC1 { get; set; }
        public int SC2 { get; set; }
        public int SC3 { get; set; }
        public int SC4 { get; set; }
        public int SC5 { get; set; }
        public int SC6 { get; set; }
        public int SC7 { get; set; }
        public int SC8 { get; set; }
        public int SC9 { get; set; }
        public int SD1 { get; set; }
        public int SD2 { get; set; }
        public int SD3 { get; set; }
        public int SD4 { get; set; }
        public int SD5 { get; set; }
        public int SD6 { get; set; }
        public int SD7 { get; set; }
        public int SD8 { get; set; }
        public int SD9 { get; set; }
        public int SE1 { get; set; }
        public int SE2 { get; set; }
        public int SE3 { get; set; }
        public int SE4 { get; set; }
        public int SE5 { get; set; }
        public int SE6 { get; set; }
        public int SE7 { get; set; }
        public int SE8 { get; set; }
        public int SE9 { get; set; }
        public int SF1 { get; set; }
        public int SF2 { get; set; }
        public int SF3 { get; set; }
        public int SF4 { get; set; }
        public int SF5 { get; set; }
        public int SF6 { get; set; }
        public int SF7 { get; set; }
        public int SF8 { get; set; }
        public int SF9 { get; set; }
        public int SG1 { get; set; }
        public int SG2 { get; set; }
        public int SG3 { get; set; }
        public int SG4 { get; set; }
        public int SG5 { get; set; }
        public int SG6 { get; set; }
        public int SG7 { get; set; }
        public int SG8 { get; set; }
        public int SG9 { get; set; }
        #endregion

        #region Small Matrix Table
        public int S1 { get; set; }
        public int EA1 { get; set; }
        public int SEA1 { get; set; }
        public int M1 { get; set; }
        public int W1 { get; set; }
        public int MW1 { get; set; }
        public int K1 { get; set; }
        public int S2 { get; set; }
        public int EA2 { get; set; }
        public int SEA2 { get; set; }
        public int M2 { get; set; }
        public int W2 { get; set; }
        public int MW2 { get; set; }
        public int K2 { get; set; }
        public int S3 { get; set; }
        public int EA3 { get; set; }
        public int SEA3 { get; set; }
        public int M3 { get; set; }
        public int W3 { get; set; }
        public int MW3 { get; set; }
        public int K3 { get; set; }
        public int S4 { get; set; }
        public int EA4 { get; set; }
        public int SEA4 { get; set; }
        public int M4 { get; set; }
        public int W4 { get; set; }
        public int MW4 { get; set; }
        public int K4 { get; set; }
        public int S5 { get; set; }
        public int EA5 { get; set; }
        public int SEA5 { get; set; }
        public int M5 { get; set; }
        public int W5 { get; set; }
        public int MW5 { get; set; }
        public int K5 { get; set; }
        public int S6 { get; set; }
        public int EA6 { get; set; }
        public int SEA6 { get; set; }
        public int M6 { get; set; }
        public int W6 { get; set; }
        public int MW6 { get; set; }
        public int K6 { get; set; }
        public int S7 { get; set; }
        public int EA7 { get; set; }
        public int SEA7 { get; set; }
        public int M7 { get; set; }
        public int W7 { get; set; }
        public int MW7 { get; set; }
        public int K7 { get; set; }
        #endregion
    }
}